### ISSUE TITLE
[Feature] 맛집탭 전체 틀 구현

### ISSUE THREAD

**Issue by haneulKimaa** [everymeals/EveryMeal_IOS#4]
## Issue

- 맛집탭 전체 틀 구현

## To-do

- [x] 맛집탭 전체 틀 만들기 (8/6?)
- [x] 상단 네비바 (HeaderView) 구현
- [x] 상단 메뉴(TopMenuView) 구현
